baseURL = ''
languageCode = 'en-us'
title = 'ThunderView'
theme = "risotto"
enableInlineShortcodes = true
timeout = "90s"

# zmv -n '(**/)(*).blkx' '$1$2.json' | bash

[mediaTypes]
  [mediaTypes.'application/json']
    suffixes = ['blkx']
  
[markup.goldmark.renderer]
  unsafe= true